app/urls.py
from django.conf.urls import url
from .views import index, dana

urlpatterns = [
    url('index', index),
    url('', index),
]

crowdFun/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path, include
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
        re_path(r'^$', views.index, name=' '),
        re_path(r'^app/', views.index, name='app'),
        re_path(r'^dana/', views.dana, name='dana'),
    path(' ', include('app.urls')),
    path('registrasi_app/', include('registrasi_app.urls')),
    path('berita/', include('berita.urls')),
    # path('', include(('registrasi_app.urls','regist'), namespace = "regist")),
    path('', include(('donasi.urls', 'kegiatanDonasi'), namespace = "kegiatanDonasi")),   
    path('', include('testimoni.urls')),
  	 path('',include('register_donatur.urls')),
]
    

register_donatur/urls.py
from django.conf.urls import url
from django.urls import path
from register_donatur import views
from .views import donatur, add_donasi, daftar_donasi, donasi_list_json

urlpatterns = [
	url('register_donatur', donatur, name='donatur'),
	url('add_donasi/', add_donasi, name='add_donasi'),
	url('daftar_donasi/', daftar_donasi, name='daftar_donasi'),
	url('donasi_list_json/', donasi_list_json, name='donasi_list_json'),
]

register_donatur/models.py
from django.db import models

# Create your models here.

class Donatur(models.Model):
	nama_program = models.CharField(max_length=27)
	nama_lengkap = models.CharField(max_length=27, default="Selvy Fitriani")
	email = models.EmailField(unique = False, default="selvyfiriani@gmail.com")
	jumlah_donasi = models.IntegerField()
	donasi_sebagai_anonim = models.BooleanField(default=False)

	# def __str__(self):
	# 	return self.nama_program

register_donatur/forms.py
from django import forms
from .models import Donatur
from donasi.views import donasiModels

class Donatur_Form(forms.Form):
    error_messages = {
        'required': 'This field is required.',
    }
    program_attrs = {
        'type': 'text',
        'class': 'donatur-form-input form-control form-style',
        'placeholder':'Nama program',
        'id': 'nama_program'
    }
    nama_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Nama lengkap',
        'id': 'nama_lengkap'
    }
    email_attrs = {
        'type':'email',
        'class': 'form-control form-style',
        'placeholder':'Email',
        'id': 'email'
    }
    donasi_attrs ={
        'type' : 'number',
        'step' : 100000,
        'class': 'form-control form-style',
        'placeholder': 'Jumlah donasi',
        'id': 'jumlah_donasi'
    }

    anonim_attrs ={
        'id':'donasi_sebagai_anonim'
    }

    OPTION = [(x.name, x.name) for x in donasiModels.objects.all()]

    nama_program = forms.ChoiceField(label='', choices=OPTION)
    nama_lengkap = forms.CharField(label='', required=True, max_length=27, widget=forms.widgets.TextInput(attrs=nama_attrs))
    email = forms.EmailField(label ='', required=True, widget=forms.TextInput(attrs=email_attrs))
    jumlah_donasi = forms.IntegerField(label='', required=True, min_value=100000, widget=forms.NumberInput(attrs=donasi_attrs))
    donasi_sebagai_anonim = forms.BooleanField(label="Donasi sebagai anonim", widget=forms.CheckboxInput(attrs=anonim_attrs), required=False) 

    def clean(self):
        cleaned_data = super().clean()
        nama_lengkap = cleaned_data.get("nama_lengkap")
        donasi_sebagai_anonim = cleaned_data.get("donasi_sebagai_anonim")
        if not donasi_sebagai_anonim and not nama_lengkap:
            raise forms.ValidationError(
                "Nama kosong"
            )
            
# class Meta:
#     model = Donatur
#     fields = ['nama_program', 'nama_lengkap', 'email', 'jumlah_donasi', 'donasi_sebagai_anonim']

register_donatur/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from .models import Donatur
from .forms import Donatur_Form
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Sum
import json

response = {'author': "Selvy Fitriani"}

# Create your views here.
def donatur(request) :
    donatur = Donatur.objects.all()
    response['donatur'] = donatur
    response['Donatur_Form'] = Donatur_Form
    return render(request, 'donatur.html', response)

@csrf_exempt
def add_donasi(request) :
    form = Donatur_Form(request.POST or None)
    if(request.method == 'POST'):
        # if 'nama_program' in request.POST:
        nama_program = request.POST["nama_program"]
        # else:
        #     nama_program = "Program tidak terdefinisi"
        if request.user.is_authenticated:
            nama_lengkap = request.user.first_name
            email = request.user.email
        else :
            nama_lengkap = 'Anonim'
            email = 'Not found'
        jumlah_donasi = request.POST["jumlah_donasi"]
        status = True
        if request.POST.get("donasi_sebagai_anonim"):
            donatur = Donatur(nama_program= nama_program, nama_lengkap=nama_lengkap, email= email,
            jumlah_donasi= jumlah_donasi, donasi_sebagai_anonim=True)
        else:
            donatur = Donatur(nama_program= nama_program, nama_lengkap=nama_lengkap, email= email,
            jumlah_donasi=jumlah_donasi, donasi_sebagai_anonim=False)
        donatur.save()
        # return HttpResponse(json.dumps({'is_success':status, 'is_yey':'yay'}), content_type = 'application/json') 
        return JsonResponse({'is_success':status, 'is_yey':'yay'}) 
        # return render(request, 'donatur.html', response)
    else:
        status = False
        # return HttpResponse(json.dumps({'is_success':status, 'is_yey':'nay'}), content_type = 'application/json')
        return JsonResponse({'is_success':status, 'is_yey':'nay'}) 
        # HttpResponseRedirect('/register_donatur/')
    # return JsonResponse({'is_success':status, 'is_yey':'yay'})

def donasi_list_json(request) :
    donasi = [obj.as_dict() for obj in Donatur.objects.all().filter(email = request.user.email)]
    return JsonResponse({"results" : donasi}, content_type = 'application/json')

def daftar_donasi(request):
    if request.user.is_authenticated:
        if 'nama' not in request.session:
            request.session['nama'] = request.user.first_name + " " + request.user.last_name
        if 'username' not in request.session:
            request.session['username'] = request.user.username
        if 'email' not in request.session:
            request.session['email'] = request.user.email
        if request.user.is_active:
            donatur = Donatur.objects.all().filter(email = request.user.email)
            response['donatur'] = donatur
            response['Donatur_Form'] = Donatur_Form
            response['total'] = Donatur.objects.all().filter(email = request.user.email).aggregate(Sum('jumlah_donasi'))['jumlah_donasi__sum']
            return render(request, 'daftar_donasi.html', response)
        else:
            return render(request, 'belum_login.html', {})
    else:
        return render(request, 'belum_login.html', {})

register_donatur/templates/belum_login.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<title>Crowd Funding Sinar Perak</title>
<link rel="shortcut icon" type="image/png" href="https://i.ibb.co/kSyxkJf/care.png"/>
<head>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'styleCrowdFun.css' %}" />
<script type="text/javascript" src="jquery-1.8.3.js"></script>
<script type="text/javascript">
   $(window).bind("load resize slid.bs.carousel", function() {
  var imageHeight = $(".active .holder").height();
  $(".controllers").height( imageHeight );
  console.log("Slid");
});
</script>

	{% include "navbar.html" %}

</head>
<body>
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">    

<!-- HEADER -->
<div class="carousel fade-carousel slide" data-ride="carousel" data-interval="4000" id="bs-carousel">
  <!-- Overlay -->
  <div class="overlay"></div>

 
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item slides active">
      <div class="slide-1"></div>
      <div class="hero">
        <hgroup>
         	 <h1>Maaf!</h1>        
             <h3>Anda belum  login. Silakan login terlebih dahulu. </h3>
             </hgroup>
      </div>
    <div class="item slides">
      <div class="slide-3"></div>
    </div>
  </div> 
</div>

{% include "footer.html" %}

</body>
</html>

register_donatur/templates/daftar_donasi.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<title>Crowd Funding Sinar Perak</title>
<link rel="shortcut icon" type="image/png" href="https://i.ibb.co/kSyxkJf/care.png"/>
<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'styleCrowdFun.css' %}" />
<script type="text/javascript" src="jquery-1.8.3.js"></script>
<script type="text/javascript">
   $(window).bind("load resize slid.bs.carousel", function() {
  var imageHeight = $(".active .holder").height();
  $(".controllers").height( imageHeight );
  console.log("Slid");
});
</script>

  {% include "navbar.html" %}

</head>
<body>
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">    

<!-- HEADER -->
<div class="carousel fade-carousel slide" data-ride="carousel" data-interval="4000" id="bs-carousel">
  <!-- Overlay -->
  <div class="overlay"></div>

 
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item slides active">
      <div class="slide-1"></div>
      <div class="hero">
        <hgroup>
           <style>
#customers {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  background-color: grey;
  border: 1px solid black;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: black;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: center;
  background-color: grey;
  color: black;
}
</style>
</head>
<body>


<p> Total Donasi : {{total}} </p>
<table id="customers">
  <tr>
    <th></th>
    <th>Nama Program</th>
    <th>Jumlah Donasi</th>
  </tr>

  {% for don in donatur %}
  <tr>
    <th> <image src="https://image.flaticon.com/icons/svg/148/148836.svg" style="size:"></th>
    <th>{{don.nama_program}}</th>
    <th>{{don.jumlah_donasi}}</th>
  </tr>
  {% endfor %}

</table>

</body>
        </hgroup>
      </div>
    <div class="item slides">
      <div class="slide-3"></div>
    </div>
  </div> 
</div>

{% include "footer.html" %}

</body>
</html>

register_donatur/templates/donatur.html
{% extends 'template.html' %}
{% load static %}}
{% block content %}

        <div class = "bg-regist">
            <center>
            <h1>Register Donatur</h1>
            <div class="card kartu" style="">
                <div class="card-body">
                    <h5 class="card-title judul-card">Terimakasih telah berbuat baik</h5>
                    <!-- Form -->
                    <section name="form" class="form">
                        <div class="flex-wrap d-flex content-section container-fluid bd-highlight text-white" id="contact-form"></div>
                            <!-- <h1 style="text-align:center">Please fill this form</h1>
                            <div class="flex-fill bd-highlight">
                                <div class="img-contact"></div>
                            </div> -->
                            <div class="p-2 flex-fill bd-highlight">
                                <form id="form-style" class="form-me" method="POST" action="{% url 'add_donasi' %}">
                                    {% if user.is_authenticated %}
                                        {% csrf_token %}
                                        {{ Donatur_Form.nama_program }}
                                        <p>Nama : {{user.first_name}} {{user.last_name}}</p>
                                        <p>Email : {{user.email}}</p>
                                        {{ Donatur_Form.jumlah_donasi }}
                                        <p>Donasi Sebagai Anonim {{ Donatur_Form.donasi_sebagai_anonim }}</p>
                                    {% else %}
                                        {% csrf_token %}
                                        {{ Donatur_Form }}
                                    {% endif %}
                                    <button id="submit" type="submit" class="btn-submit btn btn-primary btn-style" value="Submit">Kirim</button>
                                    <br>
                                </form>
                            </div>
                        </div>
                    </section>
                    <!-- <button id="history" type="button" class="btn-submit btn btn-primary btn-style" onclick="displayHistory()">Lihat Riwayat Donasi</button> -->
                </div>
            </div>
            </center>

            <!-- <section name="table-history">
                <table class="table table-responsive table-striped" id="list_donasi">
                    <thead>
                        <tr style="text-align:center">
                            <th>Nama Program</th>
                            <th>Jumlah Donasi</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </section> -->
        </div>

        <script>

            $('#form-style').on('submit', function (event) {
                event.preventDefault();
                console.log("Form Submitted!");
                saveData();
            });

            function saveData() {
                var csrftoken = $("[name=csrfmiddlewaretoken]").val();
                var program = $('#id_nama_program option:selected').text();
                var donasi = $('#jumlah_donasi').val();
                var anonim = $('#donasi_sebagai_anonim').val();
                console.log(program)
                $.ajax({
                    method: 'POST',
                    url: "/add_donasi/",
                    headers: {
                        "X-CSRFToken": csrftoken,
                    },
                    data: {
                        'nama_program': program,
                        'nama_lengkap': $('#nama_lengkap').val(),
                        'email': $('#email').val(),
                        'jumlah_donasi': donasi,
                        'donasi_sebagai_anonim': anonim,
                    },
                    success: function(result) {
                        if (result.is_success) {
                            $('#nama_program').val('');
                            $('#nama_lengkap').val('');
                            $('#email').val('');
                            $('#jumlah_donasi').val('');
                            $('#donasi_sebagai_anonim').val('');
                            // $('.error-message p').replaceWith("<p class='success'>You have successfully subscribed!</p>");
                            alert("Terimakasih sudah berbuat baik!")
                            console.log("Successfully add data");
                        } else {
                            console.log("gagal")
                            alert("Maaf, anda tidak bisa berdonasi")
                        }
                    },
                    error: function () {
                        alert("Error, cannot save data to database");
                    }
                })
            }

            //  function displayHistory() {
            //     $.ajax({
            //         method: "GET",
            //         url: "donasi_list_json",
            //         success: function (response) {
            //             var array = response.results
            //             if (array.length === 0) {
            //                 $('#list-donasi').append('<span class="list-group-item alert alert-danger text-center" role="alert"> Tidak ada teman di dalam daftar teman Anda</span>')
            //             }
            //             else {
            //                 for (var i = 0; i < array.length; i++) {
            //                     var html = '<tr>' +
            //                                 '<td>' + array[i].nama_program + '</td>' + 
            //                                 '<td>' + array[i].jumlah_donasi + '</td>' + 
            //                                 '</tr>';
            //                     $('tbody').append(html);
            //                 }
            //             }
            //         },
            //         error: function(error){
            //             alert("no one :') ")
            //         }
            //     });
            // };

        </script>        

{% endblock %}

register_donatur/templates/footer.html
{% load staticfiles %}
{% load static %}

    <!-- Footer -->
    <footer class="footer-bs">
        <div class="row">
          <div class="col-md-6 footer-brand animated fadeInLeft">
              <h2><img src="https://image.ibb.co/ig1KzU/help.png" width="50"> Sinar Perak Foundation</h2>
                <p>Yayasan kami menyediakan teknologi sebagai sarana untuk berbagi dengan sesama</p>
                <p>© 2018 Kelompok 9 PPW-C, All rights reserved</p>
            </div>
          <div class="col-md-6 footer-social animated fadeInDown">
              <h4>Follow Us</h4>
                  <a href="#"><img src="https://image.ibb.co/f55q69/google-plus.png" alt="google-plus" border="0" width="40"></a>
                  <a href="#"><img src="https://i.imgur.com/N0uAHut.png" alt="google-plus" border="0" width="40"></a>
                  <a href="#"><img src="https://i.imgur.com/XPsWABs.png" alt="google-plus" border="0" width="40"></a>
                  <a href="#"><img src="https://i.imgur.com/IhQmY3h.png" alt="google-plus" border="0" width="40"></a>
            </div>
        </div>
    </footer>
    

register_donatur/templates/navbar.html
{% load staticfiles %}
{% load static %}

 <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- <a class="navbar-brand"><img src="https://image.ibb.co/ig1KzU/help.png" alt="home" border="0" width="50"></a> -->
          	<a class="navbar-brand" href=" ">Sinar Perak Foundation</a>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-2">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/programdonasi/">Program Donasi</a></li>
            <li><a href="/galangdana/">Galang Dana</a></li>
            <li><a href="/berita/">Berita</a></li>

            <li>
              <a class="btn btn-default btn-outline btn-circle collapsed"  data-toggle="collapse" href="#" aria-expanded="false" aria-controls="nav-collapse2">Daftar</a>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->

register_donatur/templates/template.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html>
    <title>Crowd Funding Sinar Perak</title>
    <link rel="shortcut icon" type="image/png" href="https://i.ibb.co/kSyxkJf/care.png"/>
    <head>
	    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'styleCrowdFun.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'styleRegist.css' %}" />
    </head>
    <body>
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        {% include "navbar.html" %}
        {% block content %} {% endblock %}
        {% include "footer.html" %}
    </body>
</html>