app/urls.py
from django.conf.urls import url
from .views import index, dana

urlpatterns = [
    url('index', index),
    url('', index),
]

crowdFun/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path, include
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
        re_path(r'^$', views.index, name=' '),
        re_path(r'^app/', views.index, name='app'),
        re_path(r'^dana/', views.dana, name='dana'),
    path(' ', include('app.urls')),
    path('registrasi_app/', include('registrasi_app.urls')),
    path('berita/', include('berita.urls')),
    # path('', include(('registrasi_app.urls','regist'), namespace = "regist")),
    path('', include(('donasi.urls', 'kegiatanDonasi'), namespace = "kegiatanDonasi")),   
    path('', include('testimoni.urls')),
  	 path('',include('register_donatur.urls')),
]
    

donasi/urls.py
from django.urls import re_path

from .views import donasi
app_name = 'donasi'
urlpatterns = [
    re_path(r'^donasi', donasi ,name= "donasi"),
    # re_path('<str:event_site>/', detail, name='details'),
]

app/templates/dana.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<title>Crowd Funding Sinar Perak</title>
<head>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'styleCrowdFun.css' %}" />

	{% include "navbar.html" %}

</head>
<body>
<div class="error-page">
    <h2>Oops!</h2>
    <h1 class="404error"> Mohon Maaf!</h1>
    <h2 class="404error">Program Galang Dana Sedang Dalam Perbaikan</h2>    
    
    <div class="error-actions">
        <a href="{% url ' ' %}" class="btn btn-primary btn-lg">
            Kembali</a>
    </div>
</div>
{% include "footer.html" %}

</body>
</html>

app/templates/footer.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<title>Crowd Funding Sinar Perak</title>
<head>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'styleCrowdFun.css' %}" />
</head>
<body>
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

  <div class="row" style="text-align:center;">
  </div>
    <!----------- Footer ------------>
    <footer class="footer-bs">
        <div class="row">
          <div class="col-md-6 footer-brand animated fadeInLeft">
              <h2><img src="https://image.ibb.co/ig1KzU/help.png" width="50"> Sinar Perak Foundation</h2>
                <p>Yayasan kami menyediakan teknologi sebagai sarana untuk berbagi dengan sesama</p>
                <p>© 2018 Kelompok 9 PPW-C, All rights reserved</p>
            </div>
          <div class="col-md-6 footer-social animated fadeInDown">
              <h4>Follow Us</h4>
                  <a href="#"><img src="https://image.ibb.co/f55q69/google-plus.png" alt="google-plus" border="0" width="40"></a>
                  <a href="#"><img src="https://i.imgur.com/N0uAHut.png" alt="google-plus" border="0" width="40"></a>
                  <a href="#"><img src="https://i.imgur.com/XPsWABs.png" alt="google-plus" border="0" width="40"></a>
                  <a href="#"><img src="https://i.imgur.com/IhQmY3h.png" alt="google-plus" border="0" width="40"></a>
            </div>
        </div>
    </footer>
    

</body>
</html>

app/templates/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<title>Crowd Funding Sinar Perak</title>
<link rel="shortcut icon" type="image/png" href="https://i.ibb.co/kSyxkJf/care.png"/>
<head>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'styleCrowdFun.css' %}" />
<script type="text/javascript" src="jquery-1.8.3.js"></script>
<script type="text/javascript">
   $(window).bind("load resize slid.bs.carousel", function() {
  var imageHeight = $(".active .holder").height();
  $(".controllers").height( imageHeight );
  console.log("Slid");
});
</script>

	{% include "navbar.html" %}

</head>
<body>
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">    

<!-- HEADER -->
<div class="carousel fade-carousel slide" data-ride="carousel" data-interval="4000" id="bs-carousel">
  <!-- Overlay -->
  <div class="overlay"></div>

  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#bs-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#bs-carousel" data-slide-to="1"></li>
    <li data-target="#bs-carousel" data-slide-to="2"></li>
  </ol>
  
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item slides active">
      <div class="slide-1"></div>
      <div class="hero">
        <hgroup>
            <!-- user authenticated -->
                {% if user.is_authenticated %}
                <h1>Selamat Datang</h1>
                <hr>
                <h2>{{user.first_name}} {{user.last_name}}</h2>
                <hr>
                <h3>Sebar Kebaikan Kepada Sesama Akan Membuat Kamu Bahagia</h3>
            <!-- end -->
                {% else %}
                <h1>Selamat Datang!</h1>        
                <h3>Sebar Kebaikan Kepada Sesama Akan Membuat Kamu Bahagia</h3>
                {% endif %}
        </hgroup>
        <a href="{% url 'kegiatanDonasi:donasi' %}" class="btn btn-hero btn-lg" role="button">Mulai Donasi</a>
      </div>
    </div>
    <div class="item slides">
      <div class="slide-2"></div>
      <div class="hero">        
        <hgroup>     
            <h1>Wujudkan Mimpi Mereka</h1>
        </hgroup>       
        <a href="{% url 'kegiatanDonasi:donasi' %}" class="btn btn-hero btn-lg" role="button">Mulai Donasi</a>
      </div>
    </div>
    <div class="item slides">
      <div class="slide-3"></div>
      <div class="hero">        
        <hgroup>        
            <h1>Berbagi kebahagiaan</h1>
        </hgroup>
        <a href="{% url 'kegiatanDonasi:donasi' %}" class="btn btn-hero btn-lg" role="button">Mulai Donasi</a>
      </div>
    </div>
  </div> 
</div>
   
   <!-- ADA APA DISINI -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<div class="icon-box-3-center-section secpaddingTB60 ">
    <div class="container">
    	<div class="row ">
    	    <div class="col-md-12 text-center"> 
    	        <h2 class="section-title ">Ada Apa Disini?</h2>
    	 </div>
    	 <div class="border text-center"></div>
    	</div>  
	    <div class="row">
	     <div class="col-md-4 text-center"> 
	    <div class="icon-box">
                        <div class="icon-md">
                            <img src="https://image.ibb.co/gJOzzU/charity.png" alt="charity" border="0" width="100">
                        </div>
                        <h3 class="section-title">Donasi</h3>
                    </div>
	</div>
	      <div class="col-md-4 text-center"> 
	    <div class="icon-box">
                        <div class="icon-md">
                            <img src="https://image.ibb.co/crPTtp/newspaper.png" alt="newspaper" border="0" width="100">
                        </div>
                        <h3 class="section-title">Berita Terkini</h3>
                    </div>
	</div>
	      <div class="col-md-4 text-center"> 
	    <div class="icon-box">
                        <div class="icon-md">
                            <img src="https://image.ibb.co/kgKuYp/donation.png" alt="donation" border="0" width="100">
                        </div>
                        <h3 class="section-title">Galang Dana</h3>
                    </div>
	</div>
</div>
     </div>
</div>

<!-- BERITA -->

<div class="pageberita">
	<h1>MATA DUNIA</h1>
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
<!-- Wrapper for slides -->
<div class="carousel-inner">
<div class="item active">
  <div class="holder col-sm-8">
    <img class="img-responsive" src="https://image.ibb.co/htnh5f/wajah-bahagia.jpg" alt="..." width="1000">
  </div>
  <div class="col-sm-4">
    <div class="carousel-caption">
    	<h2>KPAI Minta Pemerintah Penuhi Hak Dasar Anak Korban Gempa Palu</h2>
        <p>KPAI menerima pengaduan masyarakat tentang anak- anak yang mengalami trauma dan kehilangan sosok orangtua karena gempa Palu. Selain itu, mereka juga tidak memiliki sarana untuk bermain dan rekreasi.</p>
        <a href="/berita/detail/" class="btn btn-warning">Baca Selengkapnya...</a>     
    </div>
  </div>
</div>
<div class="item">
  <div class="holder col-sm-8">
    <img class="img-responsive" src="https://cdn1.katadata.co.id/media/images/thumb/2018/10/01/2018_10_01-21_33_24_4f9ca05a092bdaecc694dc8cb89009b5_960x640_thumb.jpg" alt="..." width="1000px" height="auto">
  </div>
  <div class="col-sm-4">
    <div class="carousel-caption">
    	<h2>Bantu Pemerintah Tangani Bencana, Grup Mayapada Galang Dana Rp 2 T</h2>
        <p>KPAI menerima pengaduan masyarakat tentang anak- anak yang mengalami trauma dan kehilangan sosok orangtua karena gempa Palu. Selain itu, mereka juga tidak memiliki sarana untuk bermain dan rekreasi.</p>
        <a href="/berita/detail/" class="btn btn-warning">Baca Selengkapnya...</a>      
    </div>
  </div>
</div>
</div>
<div class="controllers col-sm-8 col-xs-12">
<!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
  </ol> 
</div>
</div>
</div>

{% include "footer.html" %}

</body>
</html>

app/templates/navbar.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<title>Crowd Funding Sinar Perak</title>
<head>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'styleCrowdFun.css' %}" />
  <script src="https://apis.google.com/js/platform.js" async defer></script>
  <meta name="google-signin-client_id" content="996165362169-4u8fgn778o7ggbt564s16kpd8b5be0de.apps.googleusercontent.com">
</head>
<body>
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

 <nav class="navbar navbar-default" style="margin:0px">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url ' ' %}">
          	<span class="image-navbar"></span>Sinar Perak Foundation</a>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-2">
          <ul class="nav navbar-nav navbar-right">
 <!--            <li>
              <a class="btn btn-default btn-outline btn-circle collapsed"  data-toggle="collapse" href="#nav-collapse2" aria-expanded="false" aria-controls="nav-collapse2">Sign in</a>
            </li> -->
            <li><a href="{% url 'kegiatanDonasi:donasi' %}">Program Donasi</a></li>
            <li><a href="{% url 'dana' %}">Galang Dana</a></li>
            <li><a href="/berita/">Berita</a></li>
            <li><a href="/testimoni/">Tentang Kami</a></li>
            {% if user.is_authenticated %}
            <li><a href="/daftar_donasi/">Riwayat</a></li>
            <li>
              <a href="/registrasi_app/logout" class="btn btn-default btn-outline btn-circle collapsed">Logout</a>
            </li>
            {% else %}
            <li>
                <a href="/registrasi_app/regis" class="btn btn-default btn-outline btn-circle collapsed">Daftar/Login</a>
            </li>
            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->
    
    <script>
        function signOut() {
        var hapus = sessionStorage.setItem(nama, 0);
         alert("Anda berhasil logout")
         var auth2 = gapi.auth2.getAuthInstance();
         auth2.disconnect().then(function () { 
           console.log("hai")
         });
        }
      
        function onLoad() {
          console.log("halo")
              gapi.load('auth2', function() {
                gapi.auth2.init();
              });
           }
    </script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.0/dist/sweetalert2.all.min.js"></script>
    <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>

</body>
</html>